### ISSUE TITLE
Out of date readme

### ISSUE THREAD

**Issue by lorr1** [hyparam/csv-validator#1]
Looks like your readme is a copy from the template one. CSV parsing is a great problem. It'd be nice to see more useful information there so we can understand how the csv validator works.

For example, here's a possible readme. I just used ChatGPT lol. I'd give it a try if you haven't alread.

CsvReader Project
Overview
The CsvReader Project provides a simple yet powerful tool for reading and validating CSV (Comma-Separated Values) files. It leverages the Guard class from guardrails library to ensure the integrity of the data by applying validation rules defined in validator.py. The main feature of this project is to validate CSV files against specified formats and take corrective actions if the data does not match the expected format.

Features
CSV Validation: Ensures that CSV files match a specified format, including the correct delimiter and structure.
Corrective Actions: Utilizes the Guard class's ability to apply corrective actions (refrain in this case) when validation fails, allowing for graceful handling of errors.

Getting Started
Prerequisites
Before you begin, ensure you have met the following requirements:

* Python 3.6 or later
* pytest

Installation
Clone the repository to your local machine:

```bash
git clone https://github.com/your-repo/CsvReader.git
cd CsvReader
```
Install the required dependencies:

```bash
pip install -r requirements.txt
```

Usage
The CsvReader functionality is demonstrated through its integration with the Guard class from the guardrails library. Here's a basic example of how to use it:

```python
from guardrails import Guard
from validator import CsvMatch

# Initialize the Guard with CSV validation rules
guard = Guard.from_string(validators=[CsvMatch(delimiter=",", on_fail="refrain")])

# Example CSV input
csv_input = "header1,header2\nrow1col1,row1col2"

# Parse and validate the CSV input
raw_output, guarded_output, *rest = guard.parse(csv_input)

# Check the output
if guarded_output is not None:
    print("CSV is valid")
else:
    print("CSV validation failed")
```
Running Tests
To validate the correctness of the CsvReader's integration with the guardrails library, run the included tests using pytest:

```bash
pytest test/test_validator.py
```
Contributing
We welcome contributions! Please open an issue or submit a pull request for any enhancements, bug fixes, or improvements.

License
This project is licensed under the [MIT License](https://chat.openai.com/c/LICENSE.md) - see the LICENSE file for details.

Learn More
For more information on the guardrails library and its features, including specifying corrective actions, visit https://www.guardrailsai.com/docs/concepts/output/.

**Comment by platypii** [comment]
Fixed. Thanks for the GREAT feedback!
